/*
 * @author Victor
 */
package Visão;

import javax.swing.JOptionPane;
import prova_zetta.*;

/**
 * Inicialização da tela de EDIÇÃO DOS CARGOS.
 * Houve problemas também com o envio de dados para os objetos das interfaces como JComboBox, foram utilizadas JList e outras, porém sem sucesso
 * na visualização dos dados. 
 * Foi implementado um contador simples, apenas para saber se a ArrayList de CARGOS estava em funcionamento.
 *  
 */
public class TelaCARGOS extends javax.swing.JFrame {

    Dados dados = new Dados();

    /**
     * Creates new form TelaCARGOS
     */
    public TelaCARGOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        botaoCANCELARcargos = new javax.swing.JButton();
        botaoLISTARCARGOS = new javax.swing.JButton();
        botaoCRIARCARGO = new javax.swing.JButton();
        botaoDELETARCARGO = new javax.swing.JButton();
        LabelCARGO = new javax.swing.JLabel();
        TextoCriarCARGO = new javax.swing.JTextField();
        TextoDelCargo = new javax.swing.JTextField();
        LabelTESTE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jList1 = new javax.swing.JList<>();
        FUNDO = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opções de Cargos");
        setResizable(false);
        getContentPane().setLayout(null);

        botaoCANCELARcargos.setText("Cancelar");
        botaoCANCELARcargos.setActionCommand("");
        botaoCANCELARcargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCANCELARcargosActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCANCELARcargos);
        botaoCANCELARcargos.setBounds(190, 240, 100, 30);

        botaoLISTARCARGOS.setText("Listar cargos");
        botaoLISTARCARGOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLISTARCARGOSActionPerformed(evt);
            }
        });
        getContentPane().add(botaoLISTARCARGOS);
        botaoLISTARCARGOS.setBounds(190, 190, 100, 30);

        botaoCRIARCARGO.setText("Criar cargo");
        botaoCRIARCARGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCRIARCARGOActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCRIARCARGO);
        botaoCRIARCARGO.setBounds(30, 80, 100, 30);

        botaoDELETARCARGO.setText("Deletar cargo");
        botaoDELETARCARGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDELETARCARGOActionPerformed(evt);
            }
        });
        getContentPane().add(botaoDELETARCARGO);
        botaoDELETARCARGO.setBounds(30, 130, 100, 30);

        LabelCARGO.setForeground(new java.awt.Color(255, 255, 255));
        LabelCARGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCARGO.setText("LISTA DE CARGOS");
        getContentPane().add(LabelCARGO);
        LabelCARGO.setBounds(370, 40, 100, 20);
        getContentPane().add(TextoCriarCARGO);
        TextoCriarCARGO.setBounds(160, 80, 130, 30);
        getContentPane().add(TextoDelCargo);
        TextoDelCargo.setBounds(160, 130, 130, 30);

        LabelTESTE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelTESTE.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LabelTESTE);
        LabelTESTE.setBounds(110, 210, 40, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrados:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 210, 81, 50);

        getContentPane().add(jList1);
        jList1.setBounds(350, 80, 140, 190);

        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Fundo.jpg"))); // NOI18N
        getContentPane().add(FUNDO);
        FUNDO.setBounds(-20, -10, 570, 320);

        setSize(new java.awt.Dimension(554, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCANCELARcargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCANCELARcargosActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCANCELARcargosActionPerformed

/**
 * O botão CRIAR CARGO está em pleno funcionamento. Sugiro a adição de alguns cargos para o teste.
 *  
 */    
    
    private void botaoCRIARCARGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCRIARCARGOActionPerformed

        Cargos cargo = new Cargos();
        if (!(TextoCriarCARGO.getText().equals("") || !(TextoCriarCARGO.getText().matches("[A-Z a-z Çç]{" + TextoCriarCARGO.getText().length() + "}")))) {
            cargo.setNOME(TextoCriarCARGO.getText());
            if (dados.cadastrarCargo(cargo)) {
                JOptionPane.showMessageDialog(null, "Cargo cadastrado!!");
            } else {
                JOptionPane.showMessageDialog(null, "Cadastro de cargo inválido!!");
            }
            LabelTESTE.setText(dados.getSIZE()); // TESTE DO ARRAY
        } else {
            JOptionPane.showMessageDialog(null, "Nome inválido!!");
        }
    }//GEN-LAST:event_botaoCRIARCARGOActionPerformed

/**
 * O botão DELETAR CARGO também está em funcionamento.
 *  
 */
    
    private void botaoDELETARCARGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDELETARCARGOActionPerformed
        String nome = TextoDelCargo.getText();
        boolean removerCargo = dados.removerCargo(nome);
        if (removerCargo) {
            JOptionPane.showMessageDialog(null, "Remoção de cargo realizada!!");
            LabelTESTE.setText(dados.getSIZE()); // TESTE DO ARRAY
        } else {
            JOptionPane.showMessageDialog(null, "Remoção inválida!!");
        }
    }//GEN-LAST:event_botaoDELETARCARGOActionPerformed

/**
 * Optei por não listar os Cargos.
 *  
 */    
    
    private void botaoLISTARCARGOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLISTARCARGOSActionPerformed
        
    }//GEN-LAST:event_botaoLISTARCARGOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCARGOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCARGOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCARGOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCARGOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaCARGOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO;
    private javax.swing.JLabel LabelCARGO;
    private javax.swing.JLabel LabelTESTE;
    private javax.swing.JTextField TextoCriarCARGO;
    private javax.swing.JTextField TextoDelCargo;
    private javax.swing.JButton botaoCANCELARcargos;
    private javax.swing.JButton botaoCRIARCARGO;
    private javax.swing.JButton botaoDELETARCARGO;
    private javax.swing.JButton botaoLISTARCARGOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
