/*
 * @author Victor
 */
package Visão;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import prova_zetta.*;
import static prova_zetta.Dados.cargos;

/**
 * Aqui ocorre a inicialização da primeira interface do meu sistema. Ela possui fornece aos usuários a capacidade de cadastramento do mesmo no sistea.
 * Uma dificuldade encontrada foi como em não conseguir utilizar o CARGO do usuário, por causa da interface, que não me possibilitou cadastrar o usuário
 * completamente. Apesar da interface contê-la ela não adiciona nada ao objeto.
 * 
 */
public class TelaCadastro extends javax.swing.JFrame {

    ArrayList usuarios = new ArrayList();

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Labelcpf = new javax.swing.JLabel();
        LabelNome = new javax.swing.JLabel();
        LabelDATA = new javax.swing.JLabel();
        LabelCARGO = new javax.swing.JLabel();
        TextoCPF = new javax.swing.JTextField();
        TextoNOME = new javax.swing.JTextField();
        BotaoSAIR = new javax.swing.JButton();
        BotaoCADASTRAR1 = new javax.swing.JButton();
        TextoDIAS = new javax.swing.JTextField();
        TextoANO = new javax.swing.JTextField();
        TextoMES = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ListaCARGO = new javax.swing.JComboBox<>();
        LabelSexo = new javax.swing.JLabel();
        TextoSEXO = new javax.swing.JTextField();
        FUNDO = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro");
        setResizable(false);
        getContentPane().setLayout(null);

        Labelcpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Labelcpf.setText("CPF:");
        getContentPane().add(Labelcpf);
        Labelcpf.setBounds(140, 190, 30, 30);

        LabelNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelNome.setText("NOME:");
        getContentPane().add(LabelNome);
        LabelNome.setBounds(130, 150, 40, 30);

        LabelDATA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelDATA.setText("DATA DE NASCIMENTO:");
        getContentPane().add(LabelDATA);
        LabelDATA.setBounds(20, 230, 150, 30);

        LabelCARGO.setText("CARGO:");
        getContentPane().add(LabelCARGO);
        LabelCARGO.setBounds(70, 280, 70, 30);
        getContentPane().add(TextoCPF);
        TextoCPF.setBounds(180, 190, 200, 30);

        TextoNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNOMEActionPerformed(evt);
            }
        });
        getContentPane().add(TextoNOME);
        TextoNOME.setBounds(180, 150, 200, 30);

        BotaoSAIR.setText("SAIR");
        BotaoSAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSAIRActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoSAIR);
        BotaoSAIR.setBounds(330, 350, 90, 40);

        BotaoCADASTRAR1.setText("Cadastrar");
        BotaoCADASTRAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCADASTRAR1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoCADASTRAR1);
        BotaoCADASTRAR1.setBounds(130, 350, 90, 40);

        TextoDIAS.setToolTipText("dd");
        getContentPane().add(TextoDIAS);
        TextoDIAS.setBounds(180, 230, 40, 30);

        TextoANO.setToolTipText("yyyy");
        getContentPane().add(TextoANO);
        TextoANO.setBounds(320, 230, 60, 30);

        TextoMES.setToolTipText("mm");
        getContentPane().add(TextoMES);
        TextoMES.setBounds(250, 230, 40, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("/");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 220, 30, 50);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("/");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 220, 30, 50);

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 350, 90, 40);

        ListaCARGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCARGOActionPerformed(evt);
            }
        });
        getContentPane().add(ListaCARGO);
        ListaCARGO.setBounds(120, 280, 140, 30);

        LabelSexo.setText("SEXO:");
        getContentPane().add(LabelSexo);
        LabelSexo.setBounds(280, 280, 60, 30);

        TextoSEXO.setToolTipText("M ou F");
        getContentPane().add(TextoSEXO);
        TextoSEXO.setBounds(320, 280, 60, 30);

        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/ImagemPrincipal.jpg"))); // NOI18N
        getContentPane().add(FUNDO);
        FUNDO.setBounds(-130, 0, 700, 430);

        jMenu2.setText("Opções");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Cargos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Usuários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(541, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSAIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotaoSAIRActionPerformed

    private void TextoNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNOMEActionPerformed

    private void BotaoCADASTRAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCADASTRAR1ActionPerformed

        if (!(TextoNOME.getText().equals("") || !(TextoNOME.getText().matches("[A-Z a-z Çç]{" + TextoNOME.getText().length() + "}")))) { // TESTA SE TEM ALGO ESCRITO NO CAMPO DE NOME, NÃO TESTA SE TEM NUMERO NO NOME
            if ((TextoCPF.getText().length() == 11 && TextoCPF.getText().matches("[0-9]+"))) { // TESTA SE TEM 11 NÚMEROS NO CPF E SE É SÓ NÚMERO
                if ((TextoDIAS.getText().length() == 2 && TextoMES.getText().length() == 2 && TextoANO.getText().length() == 4)) { // TESTA SE A DATA ESTA CORRETA
                    int d = Integer.parseInt(TextoDIAS.getText());
                    int m = Integer.parseInt(TextoMES.getText());
                    if ((d > 0 && d < 31 && m > 0 && m < 13)) {
                        if (TextoSEXO.getText().equals("M") || TextoSEXO.getText().equals("m") || TextoSEXO.getText().equals("F") || TextoSEXO.getText() == "f")  {
                            if (!(ListaCARGO.getSelectedItem() == "")) { // TESTA SE O CARGO FOI COLOCADO
                                // CRIAÇÃO DOS OBJETOS
                                Usuario usuario = new Usuario(); // Declarando um objeto usuario
                                usuario.setNOME(TextoNOME.getText()); // Definindo o nome do usuario
                                usuario.setCPF(TextoCPF.getText()); // Definindo o CPF do usuario
                                String data = TextoDIAS.getText() + "/" + TextoMES.getText() + "/" + TextoANO.getText(); //Concatenando as strings para formar a DATA
                                usuario.setNascimento(data); //Definindo a data de nascimento do usuário
                                usuario.setSexo(TextoSEXO.getText());
                                usuarios.add(usuario); //Adiciona o novo usuario ao ArrayList usuario;                 
                                if (usuario.addUsuario(usuario)) {
                                    JOptionPane.showMessageDialog(null, "Usuario adicionado!!"); // Tratamento de erro
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Selecione um cargo!!"); // Tratamento de erro
                            } 
                        } else {
                            JOptionPane.showMessageDialog(null, "Digite um sexo!!"); // Tratamento de erro

                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "DATA incorreta!!"); // Tratamento de erro
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "DATA inválida!!"); // Tratamento de erro
                }
            } else {
                JOptionPane.showMessageDialog(null, "CPF inválido!!"); // Tratamento de erro
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nome inválido!!"); // Tratamento de erro

        }
    }//GEN-LAST:event_BotaoCADASTRAR1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TextoNOME.setText("");
        TextoCPF.setText("");
        TextoDIAS.setText("");
        TextoANO.setText("");
        TextoMES.setText("");
        ListaCARGO.setSelectedItem("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaCARGOS tela = new TelaCARGOS(); // Chama uma tela de CARGOS
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaUSUARIOS tela = new TelaUSUARIOS(); // Chama uma tela de usuários
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ListaCARGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCARGOActionPerformed
        for (int i = 0; i < cargos.size(); ++i) {
            String nome = cargos.get(i).getNOME();
            this.ListaCARGO.addItem(nome);
        }
    }//GEN-LAST:event_ListaCARGOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCADASTRAR1;
    private javax.swing.JButton BotaoSAIR;
    private javax.swing.JLabel FUNDO;
    private javax.swing.JLabel LabelCARGO;
    private javax.swing.JLabel LabelDATA;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelSexo;
    private javax.swing.JLabel Labelcpf;
    private javax.swing.JComboBox<String> ListaCARGO;
    private javax.swing.JTextField TextoANO;
    private javax.swing.JTextField TextoCPF;
    private javax.swing.JTextField TextoDIAS;
    private javax.swing.JTextField TextoMES;
    private javax.swing.JTextField TextoNOME;
    private javax.swing.JTextField TextoSEXO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
